import { defineConfig, globalIgnores } from 'eslint/config'
import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

export default defineConfig([
  globalIgnores([
    '.next/**', 'out/**', 'build/**', 'next-env.d.ts',
    'database/dist/**',
    'automation-hub/projects/**',   // AI-generated replay specs, regenerated by codegen
    'automation-hub/python/**',     // vendored python framework
    'test-results/**', '.playwright-mcp/**',
    'data/**', 'public/**', 'audits/**', 'coverage/**',
  ]),
  ...coreWebVitals,
  ...typescript,
  {
    // Plain CommonJS node scripts (no "type": "module" in package.json) —
    // require() is the correct/only import style here, not a lint violation.
    files: ['scripts/**/*.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // Phase-2 downgrades: these rules have too many pre-existing hits (>20)
    // to mass-fix safely in one pass. Tracked for a follow-up cleanup.
    rules: {
      // TODO(phase2): re-enable as error — 55 pre-existing hits, mostly in
      // loosely-typed API/DB glue code that needs real typing work, not a
      // mechanical fix.
      '@typescript-eslint/no-explicit-any': 'warn',
      // TODO(phase2): re-enable as error — 32 pre-existing hits. Each needs a
      // case-by-case review (derive during render vs. move to an effect) to
      // avoid changing component behavior.
      'react-hooks/set-state-in-effect': 'warn',
    },
  },
])
