import { MigrationInterface, QueryRunner } from 'typeorm'

/**
 * Upgrades app_memberships from the ordinal viewer/tester/lead role model to
 * qa/developer/custom, where qa and developer are code presets over a
 * fine-grained permission catalog and custom stores a JSON array of
 * permission keys in the new `permissions` column.
 *
 * This migration is self-contained: the JSON literals below are hardcoded
 * copies of ALL_PERMISSIONS / LEGACY_TESTER_SET / VIEW_ONLY_SET from
 * src/lib/permissions.ts at the time this migration was written. Do not
 * import from src/lib in a migration.
 */
export class UpgradeAppRoles1700000000013 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Drop the existing DEFAULT constraint on role (name is autogenerated, so find it dynamically)
    await queryRunner.query(`
      DECLARE @df NVARCHAR(128);
      SELECT @df = dc.name FROM sys.default_constraints dc
      JOIN sys.columns c ON c.default_object_id = dc.object_id
      WHERE dc.parent_object_id = OBJECT_ID('app_memberships') AND c.name = 'role';
      IF @df IS NOT NULL EXEC('ALTER TABLE app_memberships DROP CONSTRAINT [' + @df + ']');
    `)

    // 2. Widen role to VARCHAR(20) to fit 'developer'
    await queryRunner.query(`ALTER TABLE app_memberships ALTER COLUMN role VARCHAR(20) NOT NULL`)

    // 3. Restore the default, now pointing at 'qa'
    await queryRunner.query(`ALTER TABLE app_memberships ADD CONSTRAINT DF_app_memberships_role DEFAULT 'qa' FOR role`)

    // 4. Add the permissions column for custom roles
    await queryRunner.query(`ALTER TABLE app_memberships ADD permissions NVARCHAR(MAX) NULL`)

    // 5. Data migration: map old ordinal roles onto the new model
    await queryRunner.query(`UPDATE app_memberships SET role = 'qa' WHERE role = 'lead'`)

    await queryRunner.query(`
      UPDATE app_memberships
      SET role = 'custom',
          permissions = '["dashboard.view","features.view","features.create","features.edit","features.export","testcases.generate","testcases.execute","bugs.view","bugs.create","bugs.edit","bugs.delete","bugs.report","requirements.view","requirements.edit","knowledge.view","knowledge.edit","automation.view","automation.run","automation.edit","settings.view"]'
      WHERE role = 'tester'
    `)

    await queryRunner.query(`
      UPDATE app_memberships
      SET role = 'custom',
          permissions = '["dashboard.view","features.view","bugs.view","requirements.view","knowledge.view","automation.view","settings.view"]'
      WHERE role = 'viewer'
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse mapping, best-effort: qa -> lead, custom with the view-only literal -> viewer, other custom -> tester
    await queryRunner.query(`UPDATE app_memberships SET role = 'lead' WHERE role = 'qa'`)

    await queryRunner.query(`
      UPDATE app_memberships
      SET role = 'viewer'
      WHERE role = 'custom'
        AND permissions = '["dashboard.view","features.view","bugs.view","requirements.view","knowledge.view","automation.view","settings.view"]'
    `)

    await queryRunner.query(`UPDATE app_memberships SET role = 'tester' WHERE role = 'custom'`)
    await queryRunner.query(`UPDATE app_memberships SET role = 'tester' WHERE role = 'developer'`)

    await queryRunner.query(`ALTER TABLE app_memberships DROP COLUMN permissions`)

    await queryRunner.query(`
      DECLARE @df NVARCHAR(128);
      SELECT @df = dc.name FROM sys.default_constraints dc
      JOIN sys.columns c ON c.default_object_id = dc.object_id
      WHERE dc.parent_object_id = OBJECT_ID('app_memberships') AND c.name = 'role';
      IF @df IS NOT NULL EXEC('ALTER TABLE app_memberships DROP CONSTRAINT [' + @df + ']');
    `)

    await queryRunner.query(`ALTER TABLE app_memberships ALTER COLUMN role VARCHAR(10) NOT NULL`)
    await queryRunner.query(`ALTER TABLE app_memberships ADD CONSTRAINT DF_app_memberships_role DEFAULT 'tester' FOR role`)
  }
}
