import { MigrationInterface, QueryRunner } from 'typeorm'

/**
 * Phase 1 of the DB-source-of-truth migration: extends knowledge_files with
 * docType/generatedFromIntake/updatedAt, and widens its uniqueness from
 * (appSlug, filename) to (appSlug, module, filename) now that knowledge files
 * are scoped per-module. `module` itself was already added by migration 009
 * (AddModuleColumn) — this migration only adds the remaining columns and
 * swaps the unique constraint. Not yet read by runtime code.
 */
export class ExtendKnowledgeFiles1700000000022 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.columns WHERE name='module' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files ADD module VARCHAR(50) NULL
    `)

    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.columns WHERE name='docType' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files ADD docType VARCHAR(20) NOT NULL DEFAULT 'knowledge'
    `)

    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.columns WHERE name='generatedFromIntake' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files ADD generatedFromIntake BIT NOT NULL DEFAULT 0
    `)

    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.columns WHERE name='updatedAt' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files ADD updatedAt DATETIME2 NULL
    `)

    await queryRunner.query(`
      IF EXISTS (SELECT * FROM sys.key_constraints WHERE name='UQ_knowledge_app_filename')
      ALTER TABLE knowledge_files DROP CONSTRAINT UQ_knowledge_app_filename
    `)

    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='UQ_knowledge_scope' AND object_id=OBJECT_ID('knowledge_files'))
      CREATE UNIQUE INDEX UQ_knowledge_scope ON knowledge_files (appSlug, module, filename)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      IF EXISTS (SELECT * FROM sys.indexes WHERE name='UQ_knowledge_scope' AND object_id=OBJECT_ID('knowledge_files'))
      DROP INDEX UQ_knowledge_scope ON knowledge_files
    `)

    await queryRunner.query(`
      IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE name='UQ_knowledge_app_filename')
      ALTER TABLE knowledge_files ADD CONSTRAINT UQ_knowledge_app_filename UNIQUE (appSlug, filename)
    `)

    await queryRunner.query(`
      IF EXISTS (SELECT * FROM sys.columns WHERE name='updatedAt' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files DROP COLUMN updatedAt
    `)

    // DEFAULT constraints on docType/generatedFromIntake are autogenerated,
    // so find and drop them before dropping the columns (see migration 013
    // for the same pattern).
    await queryRunner.query(`
      DECLARE @df NVARCHAR(128);
      SELECT @df = dc.name FROM sys.default_constraints dc
      JOIN sys.columns c ON c.default_object_id = dc.object_id
      WHERE dc.parent_object_id = OBJECT_ID('knowledge_files') AND c.name = 'generatedFromIntake';
      IF @df IS NOT NULL EXEC('ALTER TABLE knowledge_files DROP CONSTRAINT [' + @df + ']');
    `)

    await queryRunner.query(`
      IF EXISTS (SELECT * FROM sys.columns WHERE name='generatedFromIntake' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files DROP COLUMN generatedFromIntake
    `)

    await queryRunner.query(`
      DECLARE @df2 NVARCHAR(128);
      SELECT @df2 = dc.name FROM sys.default_constraints dc
      JOIN sys.columns c ON c.default_object_id = dc.object_id
      WHERE dc.parent_object_id = OBJECT_ID('knowledge_files') AND c.name = 'docType';
      IF @df2 IS NOT NULL EXEC('ALTER TABLE knowledge_files DROP CONSTRAINT [' + @df2 + ']');
    `)

    await queryRunner.query(`
      IF EXISTS (SELECT * FROM sys.columns WHERE name='docType' AND object_id=OBJECT_ID('knowledge_files'))
      ALTER TABLE knowledge_files DROP COLUMN docType
    `)
  }
}
